workspace:
  base: /go
  path: src/github.com/vikrantaggarwal007/go

pipeline:
  test:
    image: golang:latest
    commands:
      - go vet
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go build
      - ls -ltr
  upload:
     image: plugins/s3
     settings:
       bucket: locus-test-bucket
       region: ap-southeast-1
       access_key:
          from_secret: aws_access_key_id
       secret_key:
          from_secret: aws_secret_key_id
       source: go
       target: /test/drone
     when:
      branch: [ master ]
      event: [ push ]
